version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/pixvault.com/images:/app/images
    #ports:
    #  - 3000:3000
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/data/pixvault.com/caddy:/data

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/pixvault.com/psql:/var/lib/postgresql/data/pgdata

