version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}

  tailwind:
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    volumes:
      - ./tailwind/styles.css:/tailwind/styles.css
      - ./tailwind/tailwind.config.js:/tailwind/tailwind.config.js
      - ./assets:/dst
      - ./templates:/templates
